# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc312cddd930dde75af2a3c7b682aa323a5e65fdc878ee2b6ececdee97e6ddb99b0db8a3b7f6256062291bec461e137642033aee153154f111b855af6004c5e8

test:
  secret_key_base: 45479311900b9c26fd6e82168052131a364bf68b742c81f1cb9bbe73f56172c85043c71b88b14a312cb5b6551ad8cf2a6fd00b467b7db94c2367e51b33784a1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
